In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
df=pd.read_csv('D:/aiml/computers.csv')
df

Units  Minutes
0       1       23
1       2       29
2       3       49
3       4       64
4       4       74
5       5       87
6       6       96
7       6       97
8       7      109
9       8      119
10      9      149
11      9      145
12     10      154
13     10      166

In [13]:
x=df.iloc[:,0].values
y=df.iloc[:,1].values
x,y

(array([ 1,  2,  3,  4,  4,  5,  6,  6,  7,  8,  9,  9, 10, 10],
       dtype=int64),
 array([ 23,  29,  49,  64,  74,  87,  96,  97, 109, 119, 149, 145, 154,
        166], dtype=int64))

In [1]:
plt.scatter(x,y)

NameError: name 'plt' is not defined

In [15]:
regressor=LinearRegression()
regressor.fit(x.reshape(-1,1),y)

LinearRegression()

In [16]:
print(regressor.coef_)
print(regressor.intercept_)

[15.50877193]
4.16165413533831


In [17]:
y_pred=regressor.predict(x.reshape(-1,1))
y_pred

array([ 19.67042607,  35.17919799,  50.68796992,  66.19674185,
        66.19674185,  81.70551378,  97.21428571,  97.21428571,
       112.72305764, 128.23182957, 143.7406015 , 143.7406015 ,
       159.24937343, 159.24937343])

In [18]:
r2_score(y,y_pred)

0.9874371980620736

In [19]:
y_new=np.sqrt(y)
y_new

array([ 4.79583152,  5.38516481,  7.        ,  8.        ,  8.60232527,
        9.32737905,  9.79795897,  9.8488578 , 10.44030651, 10.90871211,
       12.20655562, 12.04159458, 12.40967365, 12.88409873])

In [24]:
regressor1=LinearRegression()
regressor1.fit(x.reshape(-1,1),y)

LinearRegression()

In [25]:
print(regressor1.coef_)
print(regressor1.intercept_)

[15.50877193]
4.16165413533831


In [28]:
y_pred1=regressor1.predict(x.reshape(-1,1))
y_pred1

array([ 19.67042607,  35.17919799,  50.68796992,  66.19674185,
        66.19674185,  81.70551378,  97.21428571,  97.21428571,
       112.72305764, 128.23182957, 143.7406015 , 143.7406015 ,
       159.24937343, 159.24937343])

In [29]:
r2_score(y_new,y_pred1)

-1550.293517275347

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x.reshape(-1,1),y,test_size=0.2,random_state=0)

In [32]:
model_fit=LinearRegression()
model_fit.fit(x_train,y_train)

LinearRegression()

In [34]:
y_pred1=model_fit.predict(x_test)
y_pred1

array([112.62604341,  96.93739566,  65.56010017])

In [3]:
r2_score(y_new,y_pred1)

NameError: name 'r2_score' is not defined